#!/bin/bash

readonly COMMIT_MSG_FILE=$1
readonly COMMIT_SOURCE=$2

to_emoji () {
  echo -n $1 | perl -CO -pE 's/\\u(\p{Hex}+)/chr(hex($1))/xieg'
}

readonly emoji_merge="$(to_emoji '\U1f500')"

add_merge_emoji() {
  local msg_temp_file="$(mktemp)"
  echo "${emoji_merge} $(cat ${COMMIT_MSG_FILE})" > "${msg_temp_file}"
  cat "${msg_temp_file}" > "${COMMIT_MSG_FILE}"
  rm  "${msg_temp_file}"
}


case "${COMMIT_SOURCE}" in
  merge) # merge commit
    add_merge_emoji
  ;;
  *)
    : # do nothing
  ;;
esac
